language: java

sudo: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"

services:
- docker

before_install:
- openssl aes-256-cbc -k "$DECRYPT_KEY" -in secret-storage.json.enc -out secret-storage.json -d -md sha256

install: skip

addons:
  sonarcloud:
    organization: piggyback

script:
- if [ $TRAVIS_BRANCH != "master" ]; then mvn clean verify sonar:sonar -Dsonar.projectKey=piggy1-mvn_piggyback-user; fi
- if [ $TRAVIS_BRANCH != "master" ]; then docker build -t piggy1/user .; fi
- if [ $TRAVIS_BRANCH != "master" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
- if [ $TRAVIS_BRANCH != "master" ]; then docker push piggy1/user; fi
- if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then mvn -Pprod clean verify; fi
- if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then docker build -t user-prod .; fi
- if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then docker tag user-prod gcr.io/absolute-text-251105/piggy1-user:v4; fi
- if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then cat secret-storage.json | docker login -u _json_key --password-stdin https://gcr.io; fi
- if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then docker push gcr.io/absolute-text-251105/piggy1-user:v4; fi

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: ZVZ4IOdvmZkChg/iFNIJHmKeQTaO9yQBCfmXfdZHI3vjU7px2Hfuh3qoBoGWbTVIdlAoFMm3YdkkpdEypV3eYqk31AHlIWip/SqFrhb6hb+eoKa4z+QvSofXv6UzfLv5/INSmC6p91IwZOM0mmPHeA57grmwuoGGRqSyL0PNB9vWoG5Z4AJy3bPGzXg+RUxuyclZBkZs86KPEc2sfdGYBFstO8LCfUleo/GGGgARGuReyqKYlWG0vgikaxBvKthqcK8MvmNk9bYcpJecQxYl9G07Lv+Sx4fG1GlCxsOaxYGV3XZ5j/4mfmbyZgblZnQbzkKtcS/vn2qBD5VwFzVwYHEhfFGX+T8+aMLim2T/5Pml9IeD5auy0do4Vz6hrVMN+swrVpjNhG72i/kinLcmVsPoYL5jKZdrfv7ct3sbwaMSZiDotJLFWNtMaH3bumcVEnytgJZpPlcY/jnapPoRt5IBTeSY9NmZBM9V+DHomK5uMAJUpSiSBhQaY0YeZBJ7maOCoxjEXe5yPW4PXsKiKsOoQ0hk+Eg2+fOkMkcnVaJKPEnhCJ3QDsCvF7mZP6dXa/fIwMut4qLen0bUyr0pTC6pxSELzd3LkpCWpwzc9+xnI6qyVXt4TlhWjY7WnH0Fub5svIK/jfOBCT1g8cDvgM5G+nmzsN/NAXLgl0fDHgk=
