apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-user-canary
  namespace: production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-user
        env: canary
    spec:
      containers:
      - image: gcr.io/absolute-text-251105/piggy1-user:v8
        name: piggyback-prod-runner-user
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-user
          containerPort: 8083
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8083
status: {}
