apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-user-production
  namespace: production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-user
        env: production
    spec:
      containers:
      - image: gcr.io/omega-palace-254907/piggy1-user:v18
        name: piggyback-prod-runner-user
        env:
          - name: JASYPT_ENCRYPTOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jasypt-password
                key: password
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-user
          containerPort: 8083
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8083
status: {}
