apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-user-production
  namespace: production
spec:
  replicas: 2
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-user
        env: production
    spec:
      containers:
      - image: gcr.io/absolute-text-251105/piggy1-user:v8
        name: piggyback-prod-runner-user
        resources:
          limits:
            memory: "384Mi"
            cpu: "300m"
        imagePullPolicy: Always
        ports:
        - name: piggy-user
          containerPort: 8083
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8083
status: {}
